// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/filters": {
            "get": {
                "description": "Возвращает списки для фильтров фронтенда",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Получить доступные значения фильтров",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_repository.FilterValues"
                        }
                    }
                }
            }
        },
        "/api/v1/minerals": {
            "get": {
                "description": "Возвращает список минералов с фильтрацией и пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minerals"
                ],
                "summary": "Получить список минералов",
                "parameters": [
                    {
                        "type": "string",
                        "default": "ru",
                        "description": "Язык (ru/en)",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "normal",
                        "description": "Режим (normal/esoteric)",
                        "name": "view",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Редкость",
                        "name": "rarity",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Минимальная твёрдость",
                        "name": "hardness_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Максимальная твёрдость",
                        "name": "hardness_max",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Только российские",
                        "name": "russian_only",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ListResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/minerals/{slug}": {
            "get": {
                "description": "Возвращает полную карточку минерала",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minerals"
                ],
                "summary": "Получить минерал по slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug минерала",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "ru",
                        "description": "Язык (ru/en)",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "normal",
                        "description": "Режим (normal/esoteric)",
                        "name": "view",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Mineral"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/search": {
            "get": {
                "description": "Полнотекстовый поиск по названию, синонимам, лору и химической формуле",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Поиск минералов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "ru",
                        "description": "Язык (ru/en)",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "normal",
                        "description": "Режим (normal/esoteric)",
                        "name": "view",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ListResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_roslava_samotsvety-api_internal_domain.Esoteric": {
            "type": "object",
            "properties": {
                "chakras": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "energy_notes": {
                    "type": "string"
                },
                "healing_interpretation": {
                    "type": "string"
                },
                "metaphysical_properties": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ritual_uses": {
                    "type": "string"
                },
                "zodiac": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.GalleryImage": {
            "type": "object",
            "properties": {
                "description_en": {
                    "type": "string"
                },
                "description_ru": {
                    "type": "string"
                },
                "type": {
                    "description": "specimen, polished, jewelry, micro и т.д.",
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.Hardness": {
            "type": "object",
            "required": [
                "max",
                "min"
            ],
            "properties": {
                "max": {
                    "type": "number",
                    "maximum": 10,
                    "minimum": 1
                },
                "min": {
                    "type": "number",
                    "maximum": 10,
                    "minimum": 1
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.I18n": {
            "type": "object",
            "properties": {
                "en": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.LangData"
                },
                "ru": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.LangData"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.LangData": {
            "type": "object",
            "required": [
                "lore",
                "name"
            ],
            "properties": {
                "color": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "color_description": {
                    "type": "string"
                },
                "esoteric": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Esoteric"
                },
                "lore": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "synonyms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.Locality": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "description_en": {
                    "type": "string"
                },
                "description_ru": {
                    "type": "string"
                },
                "famous": {
                    "type": "boolean"
                },
                "is_russian": {
                    "type": "boolean"
                },
                "locality": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.Mineral": {
            "type": "object",
            "required": [
                "slug"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "gallery": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.GalleryImage"
                    }
                },
                "i18n": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.I18n"
                },
                "localities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Locality"
                    }
                },
                "main_image_url": {
                    "type": "string"
                },
                "related_minerals": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "safety_notes": {
                    "type": "string"
                },
                "scientific": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Scientific"
                },
                "slug": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.Rarity": {
            "type": "string",
            "enum": [
                "common",
                "uncommon",
                "rare",
                "very_rare"
            ],
            "x-enum-varnames": [
                "RarityCommon",
                "RarityUncommon",
                "RarityRare",
                "RarityVeryRare"
            ]
        },
        "github_com_roslava_samotsvety-api_internal_domain.Scientific": {
            "type": "object",
            "required": [
                "chemical_formula",
                "crystal_system",
                "hardness",
                "luster",
                "mineral_group",
                "rarity",
                "specific_gravity",
                "streak",
                "transparency"
            ],
            "properties": {
                "chemical_formula": {
                    "type": "string"
                },
                "cleavage": {
                    "type": "string"
                },
                "crystal_habit": {
                    "type": "string"
                },
                "crystal_system": {
                    "type": "string"
                },
                "fracture": {
                    "type": "string"
                },
                "hardness": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Hardness"
                },
                "identification_tips": {
                    "type": "string"
                },
                "ima_status": {
                    "type": "string"
                },
                "luster": {
                    "type": "string"
                },
                "mineral_group": {
                    "type": "string"
                },
                "rarity": {
                    "enum": [
                        "common",
                        "uncommon",
                        "rare",
                        "very_rare"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Rarity"
                        }
                    ]
                },
                "specific_gravity": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.SpecificGravity"
                },
                "streak": {
                    "type": "string"
                },
                "tenacity": {
                    "type": "string"
                },
                "transparency": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.SpecificGravity": {
            "type": "object",
            "required": [
                "max",
                "min"
            ],
            "properties": {
                "max": {
                    "type": "number",
                    "minimum": 1
                },
                "min": {
                    "type": "number",
                    "minimum": 1
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_repository.FilterValues": {
            "type": "object",
            "properties": {
                "colors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "countries": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hardness_range": {
                    "type": "object",
                    "properties": {
                        "max": {
                            "type": "number"
                        },
                        "min": {
                            "type": "number"
                        }
                    }
                },
                "mineral_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rarities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_handler.ListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Mineral"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
