// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/filters": {
            "get": {
                "description": "Возвращает списки доступных значений для фронтенда",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Получить значения для фильтров",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_repository.FilterValues"
                        }
                    }
                }
            }
        },
        "/api/v1/minerals": {
            "get": {
                "description": "Возвращает список самоцветов с поддержкой фильтрации, сортировки и пагинации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minerals"
                ],
                "summary": "Получить список минералов",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "type": "integer",
                        "description": "Количество на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "created_at",
                            "name",
                            "rarity",
                            "hardness"
                        ],
                        "type": "string",
                        "description": "Сортировка",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Порядок",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ru",
                            "en"
                        ],
                        "type": "string",
                        "description": "Язык",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "normal",
                            "esoteric"
                        ],
                        "type": "string",
                        "description": "Режим",
                        "name": "view",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Только российские",
                        "name": "russian_only",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Редкость",
                        "name": "rarity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Группа",
                        "name": "mineral_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Цвет",
                        "name": "color",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Минимальная твёрдость",
                        "name": "hardness_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Максимальная твёрдость",
                        "name": "hardness_max",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт новый самоцвет/минерал в базе (админка)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minerals"
                ],
                "summary": "Создать новый минерал",
                "parameters": [
                    {
                        "description": "Данные минерала",
                        "name": "mineral",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.CreateMineralRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Mineral"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slug уже существует",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/minerals/{slug}": {
            "get": {
                "description": "Возвращает полную детальную карточку самоцвета",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minerals"
                ],
                "summary": "Получить минерал по slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug минерала",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Язык",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Режим",
                        "name": "view",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Mineral"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет минерал по slug (админка)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minerals"
                ],
                "summary": "Удалить минерал",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug минерала",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/posts": {
            "get": {
                "description": "Список постов с фильтрацией и пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Получить список статей",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип (blog, guide...)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тег",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Связанный камень",
                        "name": "gem_slug",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Только опубликованные",
                        "name": "published",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт новую статью (только админ)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Создать новую статью",
                "parameters": [
                    {
                        "description": "Данные статьи",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Post"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slug уже существует",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/posts/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Получить статью по slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug статьи",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Язык",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Post"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Обновить статью",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug статьи",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.UpdatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Post"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Удалить статью",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug статьи",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/search": {
            "get": {
                "description": "Полнотекстовый поиск по названию, синонимам, lore и химической формуле (работает на ru+en)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Поиск минералов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Язык ответа",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Режим",
                        "name": "view",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ListResponse"
                        }
                    }
                }
            }
        },
        "/minerals/{slug}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minerals"
                ],
                "summary": "Обновить минерал",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug минерала",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "mineral",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.UpdateMineralRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Mineral"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "github_com_roslava_samotsvety-api_internal_domain.EntityType": {
            "type": "string",
            "enum": [
                "mineral",
                "rock",
                "gem_variety",
                "organic"
            ],
            "x-enum-varnames": [
                "TypeMineral",
                "TypeRock",
                "TypeGemVariety",
                "TypeOrganic"
            ]
        },
        "github_com_roslava_samotsvety-api_internal_domain.Esoteric": {
            "type": "object",
            "properties": {
                "chakras": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "energy_notes": {
                    "type": "string"
                },
                "healing_interpretation": {
                    "type": "string"
                },
                "metaphysical_properties": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ritual_uses": {
                    "type": "string"
                },
                "zodiac": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.GalleryImage": {
            "type": "object",
            "properties": {
                "description_en": {
                    "type": "string"
                },
                "description_ru": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.Hardness": {
            "type": "object",
            "required": [
                "max",
                "min"
            ],
            "properties": {
                "max": {
                    "type": "number",
                    "maximum": 10,
                    "minimum": 1
                },
                "min": {
                    "type": "number",
                    "maximum": 10,
                    "minimum": 1
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.I18n": {
            "type": "object",
            "properties": {
                "en": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.LangData"
                },
                "ru": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.LangData"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.LangData": {
            "type": "object",
            "required": [
                "lore",
                "name"
            ],
            "properties": {
                "color": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "color_description": {
                    "type": "string"
                },
                "esoteric": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Esoteric"
                },
                "lore": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "synonyms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.Locality": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "description_en": {
                    "type": "string"
                },
                "description_ru": {
                    "type": "string"
                },
                "famous": {
                    "type": "boolean"
                },
                "is_russian": {
                    "type": "boolean"
                },
                "locality": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.Mineral": {
            "type": "object",
            "required": [
                "slug",
                "type"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "gallery": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.GalleryImage"
                    }
                },
                "i18n": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.I18n"
                },
                "localities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Locality"
                    }
                },
                "main_image_url": {
                    "type": "string"
                },
                "related_minerals": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "safety_notes": {
                    "type": "string"
                },
                "scientific": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Scientific"
                },
                "slug": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "description": "новое",
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "mineral",
                        "rock",
                        "gem_variety",
                        "organic"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.EntityType"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.Post": {
            "type": "object",
            "required": [
                "slug",
                "title_en",
                "title_ru",
                "type"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "content_en": {
                    "type": "string"
                },
                "content_ru": {
                    "description": "Markdown или HTML",
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "excerpt_en": {
                    "type": "string"
                },
                "excerpt_ru": {
                    "type": "string"
                },
                "gem_slugs": {
                    "description": "Связанные самоцветы",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "published_at": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title_en": {
                    "type": "string"
                },
                "title_ru": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "blog",
                        "guide",
                        "history",
                        "esoteric",
                        "review"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.PostType"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.PostType": {
            "type": "string",
            "enum": [
                "blog",
                "guide",
                "history",
                "esoteric",
                "review"
            ],
            "x-enum-varnames": [
                "PostTypeBlog",
                "PostTypeGuide",
                "PostTypeHistory",
                "PostTypeEsoteric",
                "PostTypeReview"
            ]
        },
        "github_com_roslava_samotsvety-api_internal_domain.Rarity": {
            "type": "string",
            "enum": [
                "common",
                "uncommon",
                "rare",
                "very_rare"
            ],
            "x-enum-varnames": [
                "RarityCommon",
                "RarityUncommon",
                "RarityRare",
                "RarityVeryRare"
            ]
        },
        "github_com_roslava_samotsvety-api_internal_domain.Scientific": {
            "type": "object",
            "required": [
                "hardness",
                "luster",
                "mineral_group",
                "rarity",
                "specific_gravity",
                "streak",
                "transparency"
            ],
            "properties": {
                "chemical_formula": {
                    "description": "ослаблена",
                    "type": "string"
                },
                "cleavage": {
                    "type": "string"
                },
                "composition": {
                    "description": "новое",
                    "type": "string"
                },
                "crystal_habit": {
                    "type": "string"
                },
                "crystal_system": {
                    "description": "ослаблена",
                    "type": "string"
                },
                "fracture": {
                    "type": "string"
                },
                "hardness": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Hardness"
                },
                "identification_tips": {
                    "type": "string"
                },
                "ima_status": {
                    "type": "string"
                },
                "luster": {
                    "type": "string"
                },
                "mineral_group": {
                    "type": "string"
                },
                "phenomena": {
                    "description": "новое",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rarity": {
                    "enum": [
                        "common",
                        "uncommon",
                        "rare",
                        "very_rare"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Rarity"
                        }
                    ]
                },
                "rock_type": {
                    "description": "новое",
                    "type": "string"
                },
                "specific_gravity": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.SpecificGravity"
                },
                "streak": {
                    "type": "string"
                },
                "tenacity": {
                    "type": "string"
                },
                "transparency": {
                    "type": "string"
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_domain.SpecificGravity": {
            "type": "object",
            "required": [
                "max",
                "min"
            ],
            "properties": {
                "max": {
                    "type": "number",
                    "minimum": 1
                },
                "min": {
                    "type": "number",
                    "minimum": 1
                }
            }
        },
        "github_com_roslava_samotsvety-api_internal_repository.FilterValues": {
            "type": "object",
            "properties": {
                "colors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "countries": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hardness_range": {
                    "type": "object",
                    "properties": {
                        "max": {
                            "type": "number"
                        },
                        "min": {
                            "type": "number"
                        }
                    }
                },
                "mineral_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rarities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handler.CreateMineralRequest": {
            "type": "object",
            "required": [
                "i18n",
                "scientific",
                "slug",
                "type"
            ],
            "properties": {
                "gallery": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.GalleryImage"
                    }
                },
                "i18n": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.I18n"
                },
                "localities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Locality"
                    }
                },
                "main_image_url": {
                    "type": "string"
                },
                "related_minerals": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "safety_notes": {
                    "type": "string"
                },
                "scientific": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Scientific"
                },
                "slug": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "mineral",
                        "rock",
                        "gem_variety",
                        "organic"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.EntityType"
                        }
                    ]
                }
            }
        },
        "internal_handler.CreatePostRequest": {
            "type": "object",
            "required": [
                "slug",
                "title_en",
                "title_ru",
                "type"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "content_en": {
                    "type": "string"
                },
                "content_ru": {
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "excerpt_en": {
                    "type": "string"
                },
                "excerpt_ru": {
                    "type": "string"
                },
                "gem_slugs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_published": {
                    "type": "boolean"
                },
                "published_at": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title_en": {
                    "type": "string"
                },
                "title_ru": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.PostType"
                }
            }
        },
        "internal_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_handler.ListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Mineral"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.UpdateMineralRequest": {
            "type": "object",
            "properties": {
                "gallery": {
                    "description": "указатель",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.GalleryImage"
                    }
                },
                "i18n": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.I18n"
                },
                "localities": {
                    "description": "указатель — важно!",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Locality"
                    }
                },
                "main_image_url": {
                    "type": "string"
                },
                "related_minerals": {
                    "description": "указатель",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "safety_notes": {
                    "type": "string"
                },
                "scientific": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.Scientific"
                },
                "slug": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "mineral",
                        "rock",
                        "gem_variety",
                        "organic"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.EntityType"
                        }
                    ]
                }
            }
        },
        "internal_handler.UpdatePostRequest": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "content_en": {
                    "type": "string"
                },
                "content_ru": {
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "excerpt_en": {
                    "type": "string"
                },
                "excerpt_ru": {
                    "type": "string"
                },
                "gem_slugs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_published": {
                    "type": "boolean"
                },
                "published_at": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title_en": {
                    "type": "string"
                },
                "title_ru": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_roslava_samotsvety-api_internal_domain.PostType"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
